### ISSUE TITLE
Image preview hover effect

### ISSUE THREAD

**Issue by DerStimmler** [AnsgarLichter/homepage#72]
I think it would be better if you can still see the preview image when hovering above it.

This could easily be implemented by changing the opacity value for the transition.

Instead of 1 you could use 0.5 for example. This would result in something like this:

![ansgar hover](https://user-images.githubusercontent.com/43130816/192235925-b0ab37b5-6855-48f7-94b9-e62d499ad852.gif)

Another approach would be to use a `brightness` filter on the image instead of changing the opacity. This way, you're not dependent on the background color of the image container.

In addition to that it would be nice to change the cursor style to `pointer` while hovering to symbolize that the image is clickable.

**Comment by skylinersandre** [comment]
I´m also looking forward to this.
Keep on coding.
